from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'mainsite'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^people/$', views.people, name='people'),
    url(r'^hof/$', views.hof, name='hof'),
    url(r'^magazine/$', views.magazine, name='magazine'),

    
    url(r'^yearbookLogin/$', views.yearbookLogin, name='yearbookLogin'),
    url(r'^yearbook/$', views.yearbook, name='yearbook'),
    url(r'^yearbookRegister/$', views.yearbookRegister, name='yearbookRegister'),
    url(r'^yearbookResetPswd/$', views.yearbookResetPswd, name='yearbookResetPswd'),
    url(r'^yearbookUpdate/$', views.updateYearbook, name='updateYearbook'),

    url(r'^fantasyLeagueHome/$', views.fantasyLeagueHome, name='fantasyLeagueHome'),
    url(r'^fantasyLeagueMakeTeam/(?P<matchCode>[\w-]+)/$', views.fantasyLeagueMakeTeam, name='fantasyLeagueMakeTeam'),
    url(r'^fantansyLeagueSubmissions/(?P<matchCode>[\w-]+)/$', views.fantansyLeagueSubmissions, name='fantansyLeagueSubmissions'),
    url(r'^fantansyLeagueUpdatePoints/$', views.fantansyLeagueUpdatePoints, name='fantansyLeagueUpdatePoints'),
    url(r'^fantansyLeagueUpdateDailyPoints/$', views.fantansyLeagueUpdateDailyPoints, name='fantansyLeagueUpdateDailyPoints'),
    url(r'^fantasyLeagueRegister/$', views.fantasyLeagueRegister, name='fantasyLeagueRegister'),
    url(r'^fantasyLeagueLogin/$', views.fantasyLeagueLogin, name='fantasyLeagueLogin'),
    url(r'^fantasyLeagueLogout/$', views.fantasyLeagueLogout, name='fantasyLeagueLogout'),

    url(r'^contactUs/$', views.contactUs, name='contactUs'),
    url(r'^coachFeedbackForm/$', views.coachFeedbackForm, name='coachFeedbackForm'),
    url(r'^feedbackAdminLogin/$', views.feedbackAdminLogin, name='feedbackAdminLogin'),
    url(r'^feedbackAdminHome/$', views.feedbackAdminHome, name='feedbackAdminHome'),
    url(r'^getFeedbacks/$', views.getFeedbacks, name='getFeedbacks'),
    url(r'^reimbursementForm/$', views.reimbursementForm, name='reimbursementForm'),
    url(r'^pdfyearbook/$', views.yearbook_pdf, name='yearbookpdf'),
    url(r'^pdfyearbook2/$', views.yearbook_pdf2, name='yearbookpdf2'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^form_submission/$', views.form_submission, name='form_submission'),
    # url(r'^relative_submission/$', views.relative_submission, name='relative_submission'),
    # url(r'^swimming_steps/$', views.swimming_steps, name='swimming_steps'),
    # url(r'^swimming_admin_login/$', views.swimming_admin_login, name='swimming_admin_login'),
    # url(r'^swimming_admin_logout/$', views.swimming_admin_logout, name='swimming_admin_logout'),
    # url(r'^swimming_admin_responses/swimming_forms/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$', views.get_forms_on_date, name='get_forms_on_date'),
    # url(r'^swimming_admin_responses/swimming_relatives/(?P<date>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$', views.get_relatives_on_date, name='get_relatives_on_date'),
    # url(r'^swimming_admin_responses/$', views.swimming_admin_responses, name='swimming_admin_responses'),
    url(r'^response_pdf_view_AM67_admin/$', views.render_pdf_view_AM67, name='render_pdf_view_AM67'),
    # url(r'^response_pdf_view_AM78_admin/$', views.render_pdf_view_AM78, name='render_pdf_view_AM78'),
    # url(r'^response_pdf_view_AM89_admin/$', views.render_pdf_view_AM89, name='render_pdf_view_AM89'),
    # url(r'^response_pdf_view_PM56_admin/$', views.render_pdf_view_PM56, name='render_pdf_view_PM56'),
    # url(r'^response_pdf_view_PM67_admin/$', views.render_pdf_view_PM67, name='render_pdf_view_PM67'),
    # url(r'^response_pdf_view_PM78_admin/$', views.render_pdf_view_PM78, name='render_pdf_view_PM78'), 
    # url(r'^response_pdf_view_all_admin/$', views.render_pdf_view_all, name='render_pdf_view_all'), 
    # url(r'^export/$', views.export, name='export'),

    url(r'^pride/$', views.pride, name='pride'),
    url(r'^timeline/$', views.timeline, name='timeline'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^live/$', views.live, name='live'),
    url(r'^freshers/$', views.freshers, name='freshers'),
    url(r'^orientation/$', views.orientation, name='orientation'),
    url(r'^interhostel/$', views.interhostel, name='interhostel'),
    url(r'^interiit/$', views.interiit, name='interiit'),
    url(r'^weekenders/$', views.weekenders, name='weekenders'),
    url(r'^sportech/$', views.sportech, name='sportech'),
    url(r'^leagues/$', views.leagues, name='leagues'),
    url(r'^summer/$', views.summer, name='summer'),
    url(r'^bsanight/$', views.bsanight, name='bsanight'),
    url(r'^aquatics/$', views.aquatics, name='aquatics'),
    url(r'^athletics/$', views.athletics, name='athletics'),
    url(r'^badminton/$', views.badminton, name='badminton'),
    url(r'^basketball/$', views.basketball, name='basketball'),
    url(r'^cricket/$', views.cricket, name='cricket'),
    url(r'^football/$', views.football, name='football'),
    url(r'^hockey/$', views.hockey, name='hockey'),
    url(r'^ISC/$', views.ISC, name='ISC'),
    url(r'^lawntennis/$', views.lawntennis, name='lawntennis'),
    url(r'^squash/$', views.squash, name='squash'),
    url(r'^tabletennis/$', views.tabletennis, name='tabletennis'),
    url(r'^volleyball/$', views.volleyball, name='volleyball'),
    url(r'^weightlifting/$', views.weightlifting, name='weightlifting'),
]
