# Generated by Django 2.0.6 on 2018-06-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_images', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Announcements',
            new_name='Announcement',
        ),
        migrations.AddField(
            model_name='livematch',
            name='end_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='livematch',
            name='header',
            field=models.CharField(default='Test Match', max_length=500),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.AddField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Event'),
        ),
    ]
