# Generated by Django 2.0.6 on 2018-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0003_people_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='long_des',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
