# Generated by Django 2.0.6 on 2020-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_auto_20180720_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorExe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, choices=[('', 'None'), ('Athletics (Men)', 'Athletics (Men)'), ('Athletics (Women)', 'Athletics (Women)'), ('Aquatics (Men)', 'Aquatics (Men)'), ('Aquatics (Women)', 'Aquatics (Women)'), ('Badminton (Men)', 'Badminton (Men)'), ('Badminton (Women)', 'Badminton (Women)'), ('Basketball (Men)', 'Basketball (Men)'), ('Basketball (Women)', 'Basketball (Women)'), ('Cricket', 'Cricket'), ('Football', 'Football'), ('Hockey', 'Hockey'), ('Lawn Tennis (Men)', 'Lawn Tennis (Men)'), ('Lawn Tennis (Women)', 'Lawn Tennis (Women)'), ('Squash', 'Squash'), ('Table Tennis (Men)', 'Table Tennis (Men)'), ('Table Tennis (Women)', 'Table Tennis (Women)'), ('Volleyball (Men)', 'Volleyball (Men)'), ('Volleyball (Women)', 'Volleyball (Women)'), ('Weight-lifting', 'Weight-lifting')], default='', help_text='Leave blank if not capn or vice-capn', max_length=20)),
                ('name', models.CharField(help_text='Full Name', max_length=30)),
                ('entryno', models.CharField(blank=True, help_text='Leave Blank if faculty', max_length=15)),
                ('mobileno', models.CharField(blank=True, help_text='Mobile Number', max_length=15)),
                ('email', models.CharField(help_text='Email ID', max_length=30)),
                ('hostel', models.CharField(blank=True, help_text='Leave Blank if faculty', max_length=15)),
                ('fb', models.CharField(blank=True, help_text='Not required', max_length=200)),
                ('image_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, help_text='Leave blank if not applicable', max_length=20)),
                ('name', models.CharField(help_text='Full Name', max_length=30)),
                ('entryno', models.CharField(blank=True, help_text='Leave Blank if faculty', max_length=15)),
                ('mobileno', models.CharField(blank=True, help_text='Mobile Number', max_length=15)),
                ('email', models.CharField(help_text='Email ID', max_length=30)),
                ('hostel', models.CharField(blank=True, help_text='Leave Blank if faculty', max_length=15)),
                ('fb', models.CharField(blank=True, help_text='Not required', max_length=200)),
                ('image_link', models.CharField(max_length=500)),
            ],
        ),
    ]
