# Generated by Django 2.0.6 on 2020-05-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0008_comment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment2',
            name='LiveMatch',
        ),
        migrations.DeleteModel(
            name='swimmingUser',
        ),
        migrations.DeleteModel(
            name='Comment2',
        ),
    ]
