# Generated by Django 2.0.6 on 2020-05-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0009_auto_20200530_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='swimmingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=30)),
                ('entryno', models.CharField(blank=True, max_length=15)),
                ('hostel', models.CharField(blank=True, help_text='Hostel Name', max_length=30)),
                ('mobileno', models.CharField(blank=True, help_text='Mobile Number', max_length=15)),
                ('email', models.CharField(help_text='Email ID', max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('slot', models.CharField(choices=[('slotTTS_67AM', 'slotTTS_67AM'), ('slotTTS_78AM', 'slotTTS_78AM'), ('slotTTS_89AM', 'slotTTS_89AM'), ('slotTTS_56PM', 'slotTTS_56PM'), ('slotTTS_67PM', 'slotTTS_67PM'), ('slotTTS_78PM', 'slotTTS_78PM'), ('slotWFS_67AM', 'slotWFS_67AM'), ('slotWFS_78AM', 'slotWFS_78AM'), ('slotWFS_89AM', 'slotWFS_89AM'), ('slotWFS_56PM', 'slotWFS_56PM'), ('slotWFS_67PM', 'slotWFS_67PM'), ('slotWFS_78PM', 'slotWFS_78PM')], default='slotTTS_67AM', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='Swimming_forms')),
            ],
        ),
    ]
