# Generated by Django 2.0.6 on 2020-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0011_auto_20200530_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimminguser',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='Swimming_registrations/Users_pics'),
        ),
    ]
