# Generated by Django 2.0.6 on 2020-06-09 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0012_swimminguser_user_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimminguser',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='swimminguser',
            name='monthno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swimminguser',
            name='weekno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='swimminguser',
            name='image',
            field=models.ImageField(blank=True, upload_to='Swimming_registrations/Swimming_forms'),
        ),
        migrations.AlterField(
            model_name='swimminguser',
            name='slot',
            field=models.CharField(choices=[('AM67', 'AM67'), ('AM78', 'AM78'), ('AM89', 'AM89'), ('PM56', 'PM56'), ('PM67', 'PM67'), ('PM78', 'PM78')], default='AM67', max_length=20),
        ),
    ]
