# Generated by Django 2.0.6 on 2020-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0013_auto_20200609_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimminguser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='swimminguser',
            name='monthno',
        ),
        migrations.RemoveField(
            model_name='swimminguser',
            name='weekno',
        ),
        migrations.AlterField(
            model_name='swimminguser',
            name='image',
            field=models.ImageField(blank=True, upload_to='Swimming_forms'),
        ),
        migrations.AlterField(
            model_name='swimminguser',
            name='slot',
            field=models.CharField(choices=[('slotTTS_67AM', 'slotTTS_67AM'), ('slotTTS_78AM', 'slotTTS_78AM'), ('slotTTS_89AM', 'slotTTS_89AM'), ('slotTTS_56PM', 'slotTTS_56PM'), ('slotTTS_67PM', 'slotTTS_67PM'), ('slotTTS_78PM', 'slotTTS_78PM'), ('slotWFS_67AM', 'slotWFS_67AM'), ('slotWFS_78AM', 'slotWFS_78AM'), ('slotWFS_89AM', 'slotWFS_89AM'), ('slotWFS_56PM', 'slotWFS_56PM'), ('slotWFS_67PM', 'slotWFS_67PM'), ('slotWFS_78PM', 'slotWFS_78PM')], default='slotTTS_67AM', max_length=20),
        ),
    ]
