# Generated by Django 2.0.6 on 2020-06-17 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0016_swimminguserconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='swimmingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='Swimming_registrations/Swimming_forms')),
                ('date', models.DateField(default=datetime.date.today)),
                ('approvedStatus', models.BooleanField(default=False)),
                ('disapprovedStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='swimminguser',
            name='image',
        ),
    ]
