# Generated by Django 2.0.6 on 2020-06-29 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0017_auto_20200617_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='swimmingRelative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email', max_length=30)),
                ('relation', models.CharField(blank=True, help_text='Relation', max_length=30)),
                ('relativeName', models.CharField(blank=True, help_text="Relative's Name", max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='Swimming_registrations/Relative_proof')),
                ('date', models.DateField(default=datetime.date.today)),
                ('relativeCode', models.CharField(default='0000', help_text='0000 for Non-relatives', max_length=30)),
                ('approvedStatus', models.BooleanField(default=False)),
                ('disapprovedStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='swimmingform',
            name='name',
            field=models.CharField(default='', help_text='Name', max_length=30),
        ),
        migrations.AddField(
            model_name='swimmingform',
            name='relativeCode',
            field=models.CharField(default='0000', help_text='0000 for Non-relatives', max_length=30),
        ),
        migrations.AddField(
            model_name='swimmingform',
            name='usertype',
            field=models.CharField(default='', help_text='User Type', max_length=30),
        ),
        migrations.AddField(
            model_name='swimminguser',
            name='relativeCode',
            field=models.CharField(default='0000', help_text='0000 for Non-relatives', max_length=30),
        ),
    ]
