# Generated by Django 2.0.6 on 2020-10-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0022_fantasyleaguepoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleaguematch',
            name='image_link',
            field=models.CharField(default='def', max_length=500),
        ),
    ]
