# Generated by Django 2.0.6 on 2021-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0024_dailyfantasyleaguepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Inter IIT Best Player', 'Inter IIT Best Player')], default='Inter IIT Best Player', max_length=40)),
                ('team', models.CharField(blank=True, choices=[('', 'None'), ('Athletics (Men)', 'Athletics (Men)'), ('Athletics (Women)', 'Athletics (Women)'), ('Aquatics (Men)', 'Aquatics (Men)'), ('Aquatics (Women)', 'Aquatics (Women)'), ('Badminton (Men)', 'Badminton (Men)'), ('Badminton (Women)', 'Badminton (Women)'), ('Basketball (Men)', 'Basketball (Men)'), ('Basketball (Women)', 'Basketball (Women)'), ('Cricket', 'Cricket'), ('Football', 'Football'), ('Hockey', 'Hockey'), ('ISC', 'ISC'), ('Lawn Tennis (Men)', 'Lawn Tennis (Men)'), ('Lawn Tennis (Women)', 'Lawn Tennis (Women)'), ('Squash (Men)', 'Squash (Men)'), ('Squash (Women)', 'Squash (Women)'), ('Table Tennis (Men)', 'Table Tennis (Men)'), ('Table Tennis (Women)', 'Table Tennis (Women)'), ('Volleyball (Men)', 'Volleyball (Men)'), ('Volleyball (Women)', 'Volleyball (Women)'), ('Weight-lifting', 'Weight-lifting')], default='', help_text='Leave blank if not capn or vice-capn', max_length=20)),
                ('name', models.CharField(help_text='Full Name', max_length=30)),
                ('year', models.IntegerField(default=0, help_text='Year')),
                ('image_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
