# Generated by Django 2.0.6 on 2021-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0025_hof'),
    ]

    operations = [
        migrations.CreateModel(
            name='coachFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name', max_length=30)),
                ('email', models.CharField(help_text='Email', max_length=30)),
                ('feedback', models.CharField(default='', help_text='Name', max_length=500)),
                ('sports', models.CharField(choices=[('', 'None'), ('Athletics', 'Athletics'), ('Aquatics', 'Aquatics'), ('Badminton', 'Badminton'), ('Basketball', 'Basketball'), ('Cricket', 'Cricket'), ('Football', 'Football'), ('Hockey', 'Hockey'), ('ISC', 'ISC'), ('Lawn-Tennis', 'Lawn-Tennis'), ('Squash', 'Squash'), ('Table-Tennis', 'Table-Tennis'), ('Volleyball', 'Volleyball'), ('Weight-lifting', 'Weight-lifting')], default='Athletics', max_length=20)),
            ],
        ),
    ]
