# Generated by Django 3.2 on 2021-06-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0028_yearbookcomments_yearbookpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookpeople',
            name='a1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='yearbookpeople',
            name='a2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='yearbookpeople',
            name='a3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='yearbookpeople',
            name='q1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='yearbookpeople',
            name='q2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='yearbookpeople',
            name='q3',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
