# Generated by Django 3.2 on 2021-06-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0029_auto_20210605_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookpeople',
            name='oneLiner',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
