# Generated by Django 3.2 on 2021-06-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0030_yearbookpeople_oneliner'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookpeople',
            name='funFact',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
