# Generated by Django 3.2 on 2021-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0031_yearbookpeople_funfact'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearbookpeople',
            name='a4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='yearbookpeople',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='yearbookpeople',
            name='q4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='yearbookcomments',
            name='comment',
            field=models.CharField(help_text='Comment', max_length=1000),
        ),
    ]
